# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  install-packages:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: DEBIAN_FRONTEND=noninteractive apt-get update -qq && apt-get install -y git build-essential libsfml-dev g++ libqt4-dev libeigen3-dev protobuf-compiler libprotobuf-dev libdc1394-22 libdc1394-22-dev cmake libv4l-0 libopencv-dev freeglut3-dev qt5-default omniorb omniidl omniorb-nameserver libomniorb4-dev
      - checkout
      - run: make
  build-qt5:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update -qq && apt-get install -qq git
      - checkout
      - run: apt-get install -qq qtdeclarative5-dev
      - run: mkdir -p build && cd build && cmake -DUSE_QT5=true .. && cd ..
      - run: cmake -B build -DUSE_QT5=true .
      - run: make

workflows:
  version: 2
  build_all:
    jobs:
      - install-packages
      - build-qt5
